---
- name: Trigger webhook with JSON payload
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Send POST request to webhook endpoint
      ansible.builtin.uri:
        url: https://{{ eda_server }}/eda-event-streams/api/eda/v1/external_event_stream/43d1809d-d49e-4f9d-9882-93538a581ccc/post/
        method: POST
        headers:
          Authorization: "{{ playbook_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          run_this_job_template: "{{ job_template_name }}"
          use_this_value: "{{ job_template_value }}"
        status_code: 200
      register: webhook_response

    - name: Show webhook response
      ansible.builtin.debug:
        var: webhook_response
