version: 3
images:
  base_image: 
    name: 'aap25.containersarelinux.net/ansible-automation-platform-25/ee-minimal-rhel9:latest'
dependencies:
  galaxy:
    collections:
      - ansible.controller
      - ansible.hub
      - ansible.eda
      - ansible.platform
      - infra.aap_configuration
      - jboivie.utm_inventory_plugin
  system: bindep.txt
  ansible_core:
    package_pip: ansible-core==2.15.13
  ansible_runner:
    package_pip: ansible-runner==2.4.1

additional_build_files:
  - src: files/ansible.cfg
    dest: configs/ansible.cfg

additional_build_steps:
  prepend_base:
    - RUN microdnf install -y python3-pip
  prepend_galaxy:
  prepend_galaxy:
    - ENV ANSIBLE_CONFIG=/build/configs/ansible.cfg

options:
  package_manager_path: /usr/bin/microdnf
