---
- name: Install MariaDB
  hosts: dbservers
  vars:
    version = "10.9.4"
    
  tasks:
    - name: Install MariaDB-server
      ansible.builtin.package:
        name: "MariaDB-server" 
        state: latest

# will this work now`