---
- name: "Sync quay.io registry"
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Sync registry.redhat.io registry and wait up to 300 seconds
      ansible.hub.ah_ee_registry_sync:
        ah_host: aap25.containersarelinux.net
        ah_username: "{{ cred_user }}"
        ah_password: "{{ cred_pw }}"

        name: "quay.io"
        wait: true
        timeout: 300