---
- name: Deploy Dynatrace EdgeConnect
  hosts: fedora.containersarelinux.net
  become: true
  collections:
    - containers.podman

  vars:
    edgeconnect_image: "docker.io/dynatrace/edgeconnect"
    edgeconnect_yaml_template: "edgeConnect.j2"
    edgeconnect_yaml_dest: "{{ ansible_env.PWD }}/edgeConnect.yaml"
    edgeconnect_container_name: "dynatrace-edgeconnect"

  tasks:
    - name: Pull the EdgeConnect container image
      containers.podman.podman_image:
        name: "{{ edgeconnect_image }}"
        state: present

    - name: Apply the EdgeConnect configuration template
      ansible.builtin.template:
        src: "{{ edgeconnect_yaml_template }}"
        dest: "{{ edgeconnect_yaml_dest }}"
        mode: '0644'

    - name: Set SELinux context on the configuration file
      ansible.builtin.file:
        path: "{{ edgeconnect_yaml_dest }}"
        setype: container_file_t
    
    - name: Run the EdgeConnect container
      containers.podman.podman_container:
        name: "{{ edgeconnect_container_name }}"
        image: "{{ edgeconnect_image }}"
        state: started
        restart_policy: always
        mount: "type=bind,source={{ edgeconnect_yaml_dest }},destination=/edgeConnect.yaml"
        detach: true