---
- name: Preview OPA maintenance window update (final, truly working version)
  hosts: localhost
  gather_facts: true
  vars:
    rego_file_path: /home/jboivie/aap25/rego_policies/runtime/maintenance_window.rego
    target_host: opa.containersarelinux.net
  tasks:
    - name: Get local hour and timezone offset
      set_fact:
        local_hour_raw: "{{ ansible_date_time.hour }}"
        tz_offset_raw: "{{ ansible_date_time.tz_offset }}"

    - name: Parse integers from raw time values
      set_fact:
        local_hour: "{{ local_hour_raw | int }}"
        tz_offset_hours: "{{ tz_offset_raw | int // 100 }}"

    - name: Compute UTC maintenance window hours
      set_fact:
        start_hour_utc: "{{ ((local_hour | int) - 1 - (tz_offset_hours | int)) % 24 }}"
        end_hour_utc: "{{ ((local_hour | int) + 1 - (tz_offset_hours | int)) % 24 }}"

    - name: Show calculated UTC maintenance window
      debug:
        msg: |
          maintenance_start_hour := {{ start_hour_utc }}
          maintenance_end_hour := {{ end_hour_utc }}

    # - name: Replace maintenance_start_hour in rego file
    #   delegate_to: "{{ target_host }}"
    #   replace:
    #     path: "{{ rego_file_path }}"
    #     regexp: 'maintenance_start_hour\s*:=\s*\d+'
    #     replace: "maintenance_start_hour := {{ start_hour_utc }}"

    # - name: Replace maintenance_end_hour in rego file
    #   delegate_to: "{{ target_host }}"
    #   replace:
    #     path: "{{ rego_file_path }}"
    #     regexp: 'maintenance_end_hour\s*:=\s*\d+'
    #     replace: "maintenance_end_hour := {{ end_hour_utc }}"