---
- name: Check if a server is alive
  hosts: all
  gather_facts: false
  tasks:
  - name: Log into the server and check that the ping modules returns output
    ansible.builtin.ping:
      data: pong from Ansible
