---
- name: "Install System Role for Web Console"
  hosts: "{{ vm_name }}"
  become: yes

  tasks:
    - name: Stop the Cockpit service
      ansible.builtin.service:
        name: cockpit.socket
        state: started

    - name: Open Firewall for Web Console
      firewalld:
        service: cockpit
        permanent: yes
        immediate: yes
        state: enabled
