---
- name: "Close port 9090"
  hosts: "aap25.containersarelinux.net"
  become: yes

  tasks:
    - name: Stop the Cockpit service
      ansible.builtin.service:
        name: cockpit
        state: stopped
