---
- name: Configure Yara and download malware files
  hosts: host1.containersarelinux.net
  become: yes
  tasks:
    - name: Ensure /home/jboivie/malware directory exists
      file:
        path: /home/jboivie/malware
        state: directory
        owner: jboivie
        group: jboivie
        mode: '0755'

    - name: Download eicar.com
      get_url:
        url: https://secure.eicar.org/eicar.com
        dest: /home/jboivie/malware/eicar.com
        mode: '0644'
      register: download_eicar_com

    - name: Download eicar.com.txt
      get_url:
        url: https://secure.eicar.org/eicar.com.txt
        dest: /home/jboivie/malware/eicar.com.txt
        mode: '0644'

    - name: Download eicar_com.zip
      get_url:
        url: https://secure.eicar.org/eicar_com.zip
        dest: /home/jboivie/malware/eicar_com.zip
        mode: '0644'

    - name: Download eicar_com2.zip
      get_url:
        url: https://secure.eicar.org/eicarcom2.zip
        dest: /home/jboivie/malware/eicar_com2.zip
        mode: '0644'

    - name: Install Yara
      yum:
        name: yara
        state: present

    - name: Configure malware detection
      blockinfile:
        path: /etc/insights-client/malware-detection-config.yml
        create: yes
        block: |
          test_scan: false
          filesystem_scan_only: /home/jboivie/malware
      notify:
        - Restart insights-client (if necessary)

  handlers:
    - name: Restart insights-client (if necessary)
      service:
        name: insights-client
        state: restarted
        enabled: yes