---
- name: "Close port 9090"
  hosts: "aap25.containersarelinux.net"
  become: yes

  tasks:
    - name: Close Firewall port 9090
      ansible.posix.firewalld:
        service: cockpit
        permanent: yes
        immediate: yes
        state: absent
