- name: Set hostname on RHEL VM
  hosts: "{{ new_vm_name }}.containersarelinux.net"
  gather_facts: false
  become: true

  tasks:
    - name: Set a hostname specifying strategy
      ansible.builtin.hostname:
        name: "{{ new_vm_name }}.containersarelinux.net"
        use: systemd