- name: Set hostname on RHEL VM
  hosts: "{{ new_vm_name }}"
  gather_facts: false
  become: true

  tasks:
    - name: Set a hostname specifying strategy
      ansible.builtin.hostname:
        name: "{{ new_vm_name }}"
        use: systemd