---
- name: Gather advisories and display debug messages
  hosts: all
  gather_facts: false
  tasks:

    - name: Create a list for each host with advisories
      ansible.builtin.set_fact:
        hosts_with_adv: "{{ hosts_with_adv | default([]) + [{'hostname': insights_adv_host_data.display_name,
                                        'insights_id': insights_adv_host_data.inventory_id,
                                        'advisory_id': item.payload.advisory_id,
                                        'advisory_name': item.payload.advisory_name,
                                        'advisory_type': item.payload.advisory_type}] }}"
      loop: "{{ insights_adv_data }}"
      delegate_to: localhost

    - name: Debug message
      ansible.builtin.debug:
        msg:
          - "hostname: {{ item.hostname }}"
          - "insights_id: {{ item.insights_id }}"
          - "advisory_id: {{ item.advisory_id }}"
          - "advisory_name: {{ item.advisory_name }}"
          - "advisory_type:  {{ item.advisory_type }}"
      loop: "{{ hosts_with_adv }}"