---
- name: "Install System Role for Web Console"
  hosts: "{{ vm_name }}"
  become: yes

  tasks:
    - name: Restart Cockpit service
      ansible.builtin.systemd:
        name: cockpit.service
        state: started

    - name: Open Firewall for Web Console
      firewalld:
        service: cockpit
        permanent: yes
        immediate: yes
        state: enabled
