---
- name: Configure Yara and download malware files
  hosts: host1.containersarelinux.net
  become: true
  tasks:
    - name: Ensure /home/jboivie/malware directory exists
      ansible.builtin.file:
        path: /home/jboivie/malware
        state: directory
        owner: jboivie
        group: jboivie
        mode: '0755'

    - name: Download eicar.com
      ansible.builtin.get_url:
        url: https://secure.eicar.org/eicar.com
        dest: /home/jboivie/malware/eicar.com
        mode: '0644'
      register: download_eicar_com

    - name: Download eicar.com.txt
      ansible.builtin.get_url:
        url: https://secure.eicar.org/eicar.com.txt
        dest: /home/jboivie/malware/eicar.com.txt
        mode: '0644'

    - name: Download eicar_com.zip
      ansible.builtin.get_url:
        url: https://secure.eicar.org/eicar_com.zip
        dest: /home/jboivie/malware/eicar_com.zip
        mode: '0644'

    - name: Download eicar_com2.zip
      ansible.builtin.get_url:
        url: https://secure.eicar.org/eicarcom2.zip
        dest: /home/jboivie/malware/eicar_com2.zip
        mode: '0644'

    - name: Install Yara
      ansible.builtin.yum:
        name: yara
        state: present

    - name: Configure malware detection
      ansible.builtin.blockinfile:
        path: /etc/insights-client/malware-detection-config.yml
        create: true
        block: |
          test_scan: false
          filesystem_scan_only: /home/jboivie/malware
  #    notify:
  #     - Restart insights-client (if necessary)

  handlers:
    - name: Restart insights-client (if necessary)
      ansible.builtin.service:
        name: insights-client
        state: restarted
        enabled: true