---
- name: Get configuration item
  hosts: localhost
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
    table_name: "incident"  # ServiceNow table to query
    query_params:           # Additional query parameters if needed
      active: true          # Example filter: only active incidents
    order_by: "sys_created_on"  # Sort by creation time
    limit: 1                    # Limit results to one record

  tasks:
    - name: Update a configuration item
      servicenow.itsm.configuration_item:
        sys_id: "cfc976dec3002210d09ebecdd40131df"
        install_status: in_maintenance
        operational_status: repair_in_progress
        other:
          fault_count: 1
          classification: Development

    - name: Display the Config Item details
      debug:
        var: result.records

    - name: 
      debug:
        msg: "CI: {{ result.records[0].short_description }}"
      when: result.records | length > 0