---
- name: Retrieve the latest incident from the ServiceNow incident table
  hosts: localhost
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
    table_name: "incident"  # ServiceNow table to query
    query_params:           # Additional query parameters if needed
      active: true          # Example filter: only active incidents
    order_by: "sys_created_on"  # Sort by creation time
    limit: 1                    # Limit results to one record

  tasks:
    - name: Retrieve incidents by number
      servicenow.itsm.incident_info:
        number: INC0008111
      register: result



    - name: Display the latest incident details
      debug:
        var: result.records

    - name: Display the short description of the latest incident
      debug:
        msg: "Latest Incident: {{ result.records[0].short_description }}"
      when: result.records | length > 0