---
- name: Get configuration item
  hosts: localhost
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
    table_name: "incident"  # ServiceNow table to query
    query_params:           # Additional query parameters if needed
      active: true          # Example filter: only active incidents
    order_by: "sys_created_on"  # Sort by creation time
    limit: 1                    # Limit results to one record

  tasks:
    - name: Retrieve a specific configuration item by name
      servicenow.itsm.configuration_item_info:
        name: "{{ my_configuration_item }}"
      register: result

    - name: Pass variable to next job
      set_stats:
        data:
          ansible_extra_vars:
            resource_group_name: "{{ result.records.asset_tag }}"

    - name: Display the Config Item details
      debug:
        var: result.records

    - name: 
      debug:
        msg: "CI: {{ result.records[0].short_description }}"
      when: result.records | length > 0