---
- name: Get configuration item
  hosts: localhost
  gather_facts: false
  collections:
    - servicenow.itsm

  tasks:
    - name: Retrieve a specific configuration item by name
      servicenow.itsm.configuration_item_info:
        name: "{{ my_configuration_item }}"
      register: result

    - name: Pass variable to next job
      set_stats:
        data:
          resource_group_name: "{{ result.records[0].asset_tag }}"

    - name: Display the Config Item details
      debug:
        var: result.records

    - name: 
      debug:
        msg: "CI: {{ result.records[0].short_description }}"
      when: result.records | length > 0