---
- name: Wipe the CMDB tables in ServiceNow Dev instance
  hosts: localhost
  gather_facts: false
  vars:
    servicenow_instance: "{{ SN_HOST }}"
    servicenow_username: "{{ SN_USERNAME }}"
    servicenow_password: "{{ SN_PASSWORD }}"

  tasks:
    - servicenow.itsm.configuration_item_info:
        sys_class_name: cmdb_ci_server
 #       query:
 #         - os: = Linux Red Hat
 #         - category: = Hardware
        return_fields:
          - name
          - sys_id
      register: result
    - debug:
        var: result
        verbosity: 1
    - servicenow.itsm.configuration_item:
        sys_id: "{{ item.sys_id }}"
        state: absent
      loop: "{{ result.records }}"
      loop_control:
        label: "{{ item.name }}"