---
- name: Trigger UTM VM clone via local Swift daemon
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    new_vm_name: ""
    managed_by_ansible: "No"  # This will be overridden by the survey
    delete_lock: "No"         # Set via survey

  tasks:
    - name: Determine suffix based on flags
      set_fact:
        name_suffix: >-
          {{ '_ml' if managed_by_ansible | lower == 'yes' and delete_lock | lower == 'yes'
            else '_m' if managed_by_ansible | lower == 'yes'
            else '' }}

    - name: Adjust VM name based on managed_by_ansible
      set_fact:
        adjusted_vm_name: "{{ new_vm_name }}{{ name_suffix }}"

    - name: Request clone from macOS UTM daemon
      uri:
        url: "http://192.168.67.1:5050/clone"
        method: POST
        body_format: json
        body:
          name: "{{ adjusted_vm_name }}"
          template: "{{ vm_master }}"
      register: result
      failed_when: result.status >= 400

    - name: Set output vars
      set_stats:
        data:
          vm_name: "{{ result.json.name }}"
          vm_ip: "{{ result.json.ip }}"

    - name: Show VM name and IP
      debug:
        msg: "VM {{ result.json.name }} created with IP {{ result.json.ip }}"