---
- name: Register a VM in AAP inventory
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aap_inventory_name: "AAP25 inventory"
    vm_name: "ansible-vm"
    vm_ip: "192.168.67.29"

  tasks:
    - name: Lookup inventory ID
      ansible.controller.inventory:
        name: "{{ aap_inventory_name }}"
        state: list
      register: inv_info

    - name: Add host to inventory
      ansible.controller.host:
        name: "{{ vm_name }}"
        inventory: "{{ inv_info.results[0].id }}"
        enabled: true
        variables: |
          ansible_host: {{ vm_ip }}