---
- name: Trigger UTM VM clone via local Swift daemon
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    new_vm_name: "ansible-vm"

  tasks:
    - name: Request clone from macOS UTM daemon
      uri:
        url: "http://192.168.67.1:5050/clone"
        method: POST
        body_format: json
        body:
          name: "{{ new_vm_name }}"
      register: result
      failed_when: result.status >= 400

    - name: Show VM name and IP
      debug:
        msg: "VM {{ result.json.name }} created with IP {{ result.json.ip }}"