---
- name: Clone and start UTM VM
  hosts: powerbook
  gather_facts: false

  vars:
    new_vm_name: "ansible-vm"

  tasks:
    - name: Clone, randomize MAC, start VM, return IP
      shell: |
        set -e
        export PATH="/usr/local/bin:$PATH"

        MASTER_VM_UUID="66937242-61E8-44F7-8AE3-18F284522049"
        NEW_VM_NAME="{{ new_vm_name }}"

        utmctl clone "${MASTER_VM_UUID}" --name "${NEW_VM_NAME}"

        osascript <<END
        tell application "UTM"
            set vm to virtual machine named "${NEW_VM_NAME}"
            set config to configuration of vm
            set item 1 of network interfaces of config to {address:""}
            update configuration of vm with config
        end tell
        END

        utmctl start "${NEW_VM_NAME}"

        for i in {1..30}; do
          IPs=$(utmctl ip-address "${NEW_VM_NAME}" 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' || true)
          if [ -n "$IPs" ]; then
            echo "$(echo "$IPs" | head -n 1)"
            exit 0
          fi
          sleep 2
        done

        exit 1
      register: clone_output
      changed_when: true

    - name: Show VM IP
      debug:
        msg: "Cloned VM IP: {{ clone_output.stdout_lines[-1] }}"