---
- name: Clone and start UTM VM
  hosts: powerbook
  gather_facts: false

  vars:
    new_vm_name: "ansible-vm"

  tasks:
    - name: Clone, randomize MAC, start VM, return IP
      shell: |
        set -e
        export PATH="/usr/local/bin:$PATH"

        MASTER_VM_UUID="66937242-61E8-44F7-8AE3-18F284522049"
        NEW_VM_NAME="{{ new_vm_name }}"

        utmctl clone "${MASTER_VM_UUID}" --name "${NEW_VM_NAME}"


      register: clone_output
      changed_when: true

    - name: Show VM IP
      debug:
        msg: "Cloned VM IP: {{ clone_output.stdout_lines[-1] }}"