---
- name: Register new UTM VM in AAP inventory
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aap_inventory_name: "AAP25 inventory"
    vm_name: "ansible-vm"
    vm_ip: "192.168.67.29"

  tasks:
    - name: Get inventory ID for {{ aap_inventory_name }}
      ansible.controller.inventory_info:
        name: "{{ aap_inventory_name }}"
      register: inventory_result

    - name: Add host {{ vm_name }} to inventory
      ansible.controller.host:
        name: "{{ vm_name }}"
        inventory: "{{ inventory_result.inventory.id }}"
        enabled: true
        variables: |
          ansible_host: {{ vm_ip }}
      register: host_result

    - name: Confirm host registration
      debug:
        msg: "Host {{ vm_name }} with IP {{ vm_ip }} added to inventory ID {{ inventory_result.inventory.id }}"