---
- name: Generate host list from UTM Inventory
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Collect UTM hosts
      set_fact:
        utm_hosts: >-
          {{
            groups['all']
            | list
          }}

    - name: Build utm_choices safely
      set_fact:
        utm_choices: []

    - name: Append each "host (ip)" line
      set_fact:
        utm_choices: "{{ utm_choices + [item ~ ' (' ~ hostvars[item].ansible_host ~ ')'] }}"
      loop: "{{ utm_hosts }}"

    - name: Show formatted list of UTM hosts
      debug:
        var: utm_choices