---
- name: Generate host list from UTM Inventory
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Collect UTM hosts
      set_fact:
        utm_hosts: >-
          {{
            groups['all']
            | list
          }}

    - name: Build utm_choices with just host names
      set_fact:
        utm_choices: "{{ utm_hosts }}"

    - name: Show formatted list of UTM hosts
      debug:
        var: utm_choices

    - name: Make utm_choices available to next node
      set_stats:
        data:
          utm_choices: "{{ utm_choices }}"