---
- name: Trigger UTM VM clone via local Swift daemon
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    new_vm_name: ""
    managed_by_ansible: "No"  # This will be overridden by the survey

  tasks:
    - name: Adjust VM name based on managed_by_ansible
      set_fact:
        adjusted_vm_name: >-
          {{ new_vm_name ~ '_m' if managed_by_ansible | lower == 'yes' else new_vm_name }}

    - name: Request clone from macOS UTM daemon
      uri:
        url: "http://192.168.67.1:5050/clone"
        method: POST
        body_format: json
        body:
          name: "{{ adjusted_new_vm_name }}"
      register: result
      failed_when: result.status >= 400

    - name: Set output vars
      set_stats:
        data:
          vm_name: "{{ result.json.name }}"
          vm_ip: "{{ result.json.ip }}"

    - name: Show VM name and IP
      debug:
        msg: "VM {{ result.json.name }} created with IP {{ result.json.ip }}"