---
- name: Register a VM in AAP inventory
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aap_inventory_name: "AAP25 inventory"
    aap_organization: "Default"
    vm_name: "ansible-vm"
    vm_ip: "192.168.67.29"

  tasks:
    - name: Ensure inventory exists (retrieve ID)
      ansible.controller.inventory:
        name: "{{ aap_inventory_name }}"
        organization: "{{ aap_organization }}"
        state: present
      register: inventory

    - name: Add host to inventory
      ansible.controller.host:
        name: "{{ vm_name }}"
        inventory: "{{ inventory.id }}"
        enabled: true
        variables:
          ansible_host: "{{ vm_ip }}"

    - name: Confirm host creation
      debug:
        msg: "VM '{{ vm_name }}' registered with IP {{ vm_ip }} in inventory '{{ aap_inventory_name }}'"