---
- name: Receives webhook from my playbook
  hosts: all
  sources:
    - name: Listen
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4999

  rules:
    - name: Curl command 1
      condition: event is defined
      action:
        debug:
          msg: "{{ event }}"