---
- name: Monitor AAP URL and execute job template
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - https://aap25.containersarelinux.net:9090  # URL to monitor
        delay: 15                 # Frequency of checks (in seconds)

  rules:
    - name: Web console is down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "Enable Web Console on RHEL"
          organization: "Default"  # Specify the organization name if applicable
          job_args:
            extra_vars:              # Add any additional variables if required for the job
              vm_name: "aap25.containersarelinux.net"
