---
- name: Listen for events from Github Actions
  hosts: all
  sources:
    - name: Listen for alerts from 
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5432

  rules:
    - name: OPA updated
      condition: event.payload.event == "opa_updated"
      action:
        run_job_template:
          name: "Update policies on OPA server"
          organization: Default