---
- name: Listen for repo update from Gtihub
  hosts: all
  sources:
    - name: Listen for alerts from Github
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5432

  rules:
    - name: Github repo updated
      condition: event.payload.event == "repository_updated"
      action:
        run_job_template:
          name: "Sync AAP Project"
          organization: Default
          job_args:
            extra_vars: "{{ event.payload }}"