# Use the base image
FROM registry.redhat.io/ansible-automation-platform-25/ansible-dev-tools-rhel8:latest

# Switch to root user to modify system files
USER root

# Add the custom MOTD
RUN echo "This is a demo for Tech Update..." > /etc/motd

# Optionally set the working directory
WORKDIR /root

# Set the entry point (default behavior)
CMD ["/bin/bash"]