# Use the base image
FROM registry.redhat.io/ansible-automation-platform-25/ansible-dev-tools-rhel8:latest

# Add the custom MOTD
RUN echo "Welcome to this nice custom Devcontainer for Ansible" > /etc/motd

# Optionally set the working directory
WORKDIR /root

# Set the entry point (default behavior)
CMD ["/bin/bash"]