---
- name: Export projects
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  environment:
    CONTROLLER_HOST: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    CONTROLLER_USERNAME: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    CONTROLLER_PASSWORD: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
    CONTROLLER_VERIFY_SSL: "{{ (lookup('env', 'CONTROLLER_VERIFY_SSL') | default('true')) | bool }}"


  tasks:
    - name: Export projects
      ansible.controller.export:
        projects: all
      register: export_results

    - name: Show results
      ansible.builtin.debug:
        var: export_results

    - name: Export projects to file
      ansible.builtin.copy:
        content: "{{ export_results | to_nice_yaml(width=50, explicit_start=true, explicit_end=true) }}"
        dest: projects.yaml