name: Build and Push Container Image with Podman

on:
  push:
    branches:
      - main
    paths:
      - 'Devcontainer/**'
      - '.github/workflows/build.yml'
      - 'rulebooks/github_webook.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug - Verify File Structure
      run: ls -R .

    - name: Install Podman
      run: |
        sudo apt update
        sudo apt install -y podman

    - name: Install QEMU for cross-architecture support
      run: |
        sudo apt update
        sudo apt install -y qemu-user-static

    - name: Log in to Red Hat Container Registry
      run: |
        echo "${{ secrets.REDHAT_PASSWORD }}" | podman login registry.redhat.io --username ${{ secrets.REDHAT_USERNAME }} --password-stdin

    - name: Log in to Quay.io
      run: |
        echo "${{ secrets.REDHAT_PASSWORD }}" | podman login quay.io --username ${{ secrets.QUAY_USERNAME }} --password-stdin

    - name: Build the container for arm64
      run: |
        podman build --platform linux/arm64 -t quay.io/jboivieredhat/ansible-local-dev:latest -f ./Devcontainer/Containerfile ./Devcontainer

    - name: Push the container to Quay.io
      run: |
        podman push quay.io/jboivieredhat/ansible-local-dev:latest

    - name: Call Webhook with HMAC
      run: |
        PAYLOAD='{"event":"container_pushed","image":"quay.io/jboivieredhat/ansible-local-dev:latest"}'
        SECRET="${{ secrets.WEBHOOK_SECRET }}"
        SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | awk '{print $2}')
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
          -d "$PAYLOAD" \
          "${{ secrets.WEBHOOK_URL }}"