name: Build and Push Container Image with Podman

on:
  push:
    branches:
      - main
    paths:
      - 'Devcontainer/**' # Trigger only when files in the Devcontainer folder change
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Install Podman
      run: |
        sudo apt update
        sudo apt install -y podman

    - name: Log in to Red Hat Container Registry
      run: |
        echo "${{ secrets.REDHAT_PASSWORD }}" | podman login registry.redhat.io --username ${{ secrets.REDHAT_USERNAME }} --password-stdin

    - name: Log in to Quay.io
      run: |
        echo "${{ secrets.REDHAT_PASSWORD }}" | podman login quay.io --username ${{ secrets.REDHAT_USERNAME }} --password-stdin

    - name: Build the container
      run: |
        podman build -t quay.io/jboivie-redhat/ansible-local-dev:latest -f Devcontainer/Containerfile .

    - name: Push the container to Quay.io
      run: |
        podman push quay.io/jboivie-redhat/ansible-local-dev:latest