name: OPA Check Folder

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths:
      - 'policy_checked_playbooks/**'
  pull_request:
    paths:
      - 'policy_checked_playbooks/**'
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pre-merge:
    # Name of test
    name: OPA-securitygate
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install conftest and add to path
        run: |
         LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
         ARCH=$(arch)
         SYSTEM=$(uname)
         wget "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_${SYSTEM}_${ARCH}.tar.gz"
         tar xzf conftest_${LATEST_VERSION}_${SYSTEM}_${ARCH}.tar.gz && echo "Extracted conftest tar archive"
         ls -la
         echo "$PWD/conftest" >>$GITHUB_PATH
         chmod a+rx conftest

      - name: Running Open Policy Agent test from rego_policies/ci_security_gate
        run: |
          cd $GITHUB_WORKSPACE
          echo "----------------------"
          echo "Running linting"
          echo "----------------------"
          for playbook in policy_checked_playbooks/*.yml; do
            echo "Running conftest on: $playbook"
            ./conftest test $playbook --policy rego_policies/ci_security_gate
          done