name: Notify AAP of OPA policy update

on:
  push:
    branches:
      - main
    paths:
      - 'rego_policies/**'

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Webhook to AAP Event Stream for OPA Update
        run: |
          # Set payload for OPA update
          PAYLOAD='{"event": "opa_updated"}'
          SECRET="${{ secrets.WEBHOOK_SECRET }}"

          # Compute the HMAC signature
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | awk '{print $2}')

          # Call the webhook for AAP 2.5
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
            -d "$PAYLOAD" \
            "${{ secrets.WEBHOOK_URL }}"